/*These exercises are based on the demo database hosted in the W3Schools tutorial. Please write the query in the row below the exercise.*/


/* 1. All values from all columns and all rows from the table Customers. */
/* your query goes here.. */

/* 2. All values from all columns and rows from the table Suppliers. */


/* 3. All values from the columns SupplierID and Country from the table Supplier. */


/* 4. All values from the columns SupplierID and Country from the table Supplier (only distinct values). */


/* 5. All values from the columns ContactName and Address from the table Customers (only distinct values). */


/* 6. All values from the column CustomerID (from the Customers Table) where the customer id is bigger than 20. */


/* 7. All values from the column CustomerID (from the Customers Table) where the customer id is smaller than 15. */


/* 8. All values of all columns of the table Suppliers where the SupplierID is bigger than 35. */


/* 9. All values of ContactName for the rows whose SupplierID is bigger than 10 on the table Suppliers. */


/* 10. The value of ContactName for the row whose SupplierID is 5. */


/* 11. The values of CustomerName for the row whose ContctName is 'Ana Trujillo'. */


/* 12. All the values of CustomerName for the rows whose City is Berlin from the table Customers. */


/* 13. All the values of CustomerName for the rows whose City is Berlin or London from the table Customers. */


/* 14. All the values of CustomerName for the rows whose City is Berlin and the CustomerID is bigger than 30 from the table Customers. */


/* 15. All the values of CustomerName for the rows whose Country is Germany and the CustomerID is bigger than 30 from the table Customers. */


/* 16. All the values of Address for the rows whose Country is Japan and the SupplierID it less than 30 from the table Suppliers. */


/* 17. All the values of Address for the rows whose Country is Japan or France from the table Suppliers (Sorted in ascending order). */


/* 18. All the values of PostalCode for the rows whose Country is Japan or France from the table Suppliers (Sorted in descending order). */


/* 19. All the values of SupplierName for the rows whose City is London or Manchester from the table Suppliers (Sorted by PostalCode in ascending order). */


/* 20. All the values of ContactName for the rows whose Country is Mexico or Sweden from the table Customers (Sorted by Address in descending order). */

