/*These exercises are based on the demo database hosted in the W3Schools tutorial.*/

/*1. Perform an inner join on CustomerID on the tables Orders and Customers.*/

/*2. The CustomerName of all the customers with at least three orders in the table Orders.*/

/*3. The OrderID of all the orders whose customer is based in Berlin.*/

/*4. The OrderID of all the orders whose associated Employee has the first name Adam.*/

/*5. The OrderID of all the orders whose associated Employee's first name starts with 'A'.*/

/*6. The OrderID of all the orders whose associated Employee's first name starts with 'A'.*/

/*7. The OrderID, Employee's LastName, FirstName and BirthDate of all the orders whose associated Employee is born after 1965.*/

/*8. The CustomerID of all the customers that have no associated order.*/

/*9. How many customers have no associated order?*/

/*10. All CustomerIDs and the number of orders they are associated with.*/

/*11. All CustomerIDs and the biggest OrderID they are associated with.*/

/*12. All CustomerIDs associated with more than 3 orders.*/


