/*These exercises are based on the demo database hosted in the W3Schools tutorial. Please write the query in the row below the exercise.*/


/* 1. Insert the row:[Macelleria, Antonio Grasso, via Sant’Anna 20, Benevento, 82019, Italy] in the table Customers. */
/* your query goes here.. */

/* 2. Write a query that returns the row that we just inserted (and no other row). */

/* 3. Write a query to insert the details of Genny Savastano to the table Suppliers. */

/* 4. Write a query that returns the row that we just inserted (and no other row). */

/* 5. Write a query that shows all the rows with a NULL value from the table Suppliers. */

/* 6. Write a query that shows all the rows with no NULL value from the table Suppliers. */

/* 7. Write a query to insert a row for Savastano Pietro in the table Suppliers, leaving the phone number as NULL. */

/* 8. Write a query that returns the row that we just inserted (and no other row) to make sure the phone number is NULL. */

/* 9. Update the phone number of Pietro Savastano in the table Suppliers to be 081 - 000000. */

/* 10. Update the row added at exercise 1 to change the CustomerName from ‘Macelleria’ to ‘Girarrosto’. */

/* 11. Update all the rows of Suppliers where the City is Napoli to have the Country Honduras. */

/* 12. Update all the rows of Customers where the city is London or Frankfurt to have the CustomerName Parenzo. */

/* 13. Delete all the rows of Customers where Country is Germany. */

/* 14. Delete the row of Customers where the CustomerID is 5. */

/* 15. Delete the rows of Customers where the city is Berlin or Monaco. */

/* 16. Delete the rows of Suppliers where the city is different from Napoli. */
