/*The first 10 CustomerName from the table Customers sorted alphabetically.*/

/*The last 15 CustomerName from the table Customers in alphabetical order.*/
/*The first 10 unique Countries from the table Customers sorted alphabetically.*/
/*The 10 Countries from the table Customers of the rows with the first 10 CustomerName sorted alphabetically.*/
/*The SupplierName that comes first in alphabetical order from the table Suppliers.*/
/*The CustomerName that comes first in alphabetical order from the table Customers where the country is Germany or USA.*/
/*The SupplierName that comes last in alphabetical order from the table Suppliers.*/
/*The SupplierID of the SupplierName that comes first in alphabetical order from the table Suppliers.*/
/*The last CustomerID from the table Customers where the country is Germany or UK.*/
/*The full last row of the table Products.*/
/*The full first row of the table Customers.*/
/*The average price from the table Products.*/
/*The average price from the table Products with the SupplierID 2.*/
/*The average price from the table Products with the CategoryID 1 or 2.*/
/*The number of items with the SupplierID 3 from the table Products.*/
/*The number of different City for the Country USA in the table Suppliers.*/
The total Quantity across all items for the OrderID 10248 from the table Orders.
The total Quantity across all items across the orders with OrderID 10248 and 10249, from the table Orders.
The total Quantity of the item with ProductID 11 across all orders in the table Order.
